name: CI

on: [push]

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Ensure changelog has been changed in this PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        changed_files=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/andrewhampton/bristow/compare/main...${GITHUB_SHA} | jq '.files[] | select(.filename == "CHANGELOG.md") | .filename' | tr -d '"')
        if [ -z "$changed_files" ]; then
          echo "CHANGELOG.md was not updated in this PR. Please add a changelog entry."
          exit 1
        fi

  test:
    name: Test on Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: dummy-key-for-tests
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3', '3.4']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
