name: CI

on: [push]

jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: dummy-key-for-tests
    strategy:
      matrix:
        ruby-version: ["3.2", "3.3", "3.4"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
